version: '3.4'

services:
  flixone.bookstore.orderservice:
    image: ${DOCKER_REGISTRY-}flixonebookstoreorderservice
    build:
      context: .
      dockerfile: FlixOne.BookStore.OrderService/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
  rabbitmq:
    image: rabbitmq:3-management
