version: '3.4'

services:
    
    sqldata:
        image: mcr.microsoft.com/mssql/server:2017-latest
    
    flixone.bookstore.userservice:
        image: flixone.bookstore.userservice
        build:
          context: ./FlixOne.BookStore.UserService
          dockerfile: Dockerfile
        depends_on:
          - sqldata